// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ymxvmwhtsqtjcmvsoqpw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlteHZtd2h0c3F0amNtdnNvcXB3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3NDUwNzgsImV4cCI6MjA2MDMyMTA3OH0.ju75r5ixwbb6kjjSFbUrJhpzZ960NnrXaDLHelhtnaQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);